---
# tasks file for deploy
- name: Install a list of packages
  apt:
    pkg:
      - default-jdk
      - maven
      - git
    update_cache: yes
    state: present
- name: Just get information about the repository whether or not it has already been cloned locally
  git:
    repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
    dest: "{{ deploy_folder }}"
    clone: yes
    update: no
- name: Build app
  shell: mvn package chdir="{{ deploy_folder }}"